{{- if and .Values.cartService.create .Values.devDeployment -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.cartService.database.secretName }}
  labels:
    app: cartservice
stringData:
  connectionString: {{ printf "%s-cart-valkey-headless:6379" .Release.Name | quote }}
{{- end -}}
