{{- if and .Values.cartService.create .Values.devDeployment }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cartService.database.secretName }}
  namespace: {{ .Release.Namespace }}
stringData:
  connectionString: {{ .Values.cartValkey.nameOverride }}:6379
{{- end -}}
